name: Deploy to production

on:
  push:
    branches:
      - main

  workflow_dispatch:
    
concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Nginx webroot
        run: |
          if [ ! -f "dist/index.html" ]; then
            echo "Ошибка: dist/index.html не найден!"
            exit 1
          fi

          if [ -f /var/www/eco-map/favicon.ico ] && [ ! -f dist/favicon.ico ]; then
            cp /var/www/eco-map/favicon.ico dist/favicon.ico
          fi

          sudo rsync -av --delete dist/ /var/www/eco-map/

          sudo chown -R www-data:www-data /var/www/eco-map/
          sudo chmod -R 755 /var/www/eco-map/
